name: devnet

services:
  geth:
    image: "ethereum/client-go:v1.14.8"
    command:
      - --networkid=48815
      - --nodiscover
      - --http
      - --http.api=eth,net,web3,debug,txpool
      - --http.addr=0.0.0.0
      - --http.corsdomain=*
      - --http.vhosts=*
      - --ws
      - --ws.api=eth,net,web3,debug,txpool
      - --ws.addr=0.0.0.0
      - --ws.origins=*
      - --syncmode=full
      - --gcmode=archive
      - --history.transactions=0
      - --history.state=0
      - --verbosity=5
      - --log.debug=true
      #- --miner.gaslimit=9000000000000
      #- --miner.gasprice=115025187511
    ports:
      - 8545:8545
      - 8546:8546
    depends_on:
      beacon-chain:
        condition: service_started
    volumes:
      - ./data/geth:/root/.ethereum
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"

  beacon-chain:
    image: "gcr.io/prysmaticlabs/prysm/beacon-chain:v5.0.3"
    command:
      - --datadir=/prysm/beacondata
      - --min-sync-peers=0
      - --genesis-state=/prysm/genesis.ssz
      - --bootstrap-node=
      - --interop-eth1data-votes
      - --chain-config-file=/config/config.yml
      - --contract-deployment-block=0
      - --chain-id=48815
      - --rpc-host=0.0.0.0
      - --grpc-gateway-host=0.0.0.0
      - --execution-endpoint=/geth/geth.ipc
      - --accept-terms-of-use
      - --suggested-fee-recipient=0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266
      - --minimum-peers-per-subnet=0
    ports:
      - 4000:4000
      - 3500:3500
    volumes:
      - ./data/prysm:/prysm
      - ./data/geth:/geth
      - ./config/config.yml:/config/config.yml:ro
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"

  validator:
    image: "gcr.io/prysmaticlabs/prysm/validator:v5.0.3"
    command:
      - --beacon-rpc-provider=beacon-chain:4000
      - --datadir=/prysm/validatordata
      - --accept-terms-of-use
      - --interop-num-validators=1
      - --interop-start-index=0
      - --chain-config-file=/config/config.yml
    depends_on:
      beacon-chain:
        condition: service_started
    volumes:
      - ./data/prysm:/prysm
      - ./config/config.yml:/config/config.yml:ro
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
